"""Add EAM fields to Equipment

Revision ID: e18591505b9a
Revises: 72a24f7dc941
Create Date: 2026-07-06 13:26:47.466645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18591505b9a'
down_revision: Union[str, None] = '72a24f7dc941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    op.add_column('equipment', sa.Column('warranty_expiry', sa.DateTime(), nullable=True))
    op.add_column('equipment', sa.Column('expected_lifetime_years', sa.Float(), nullable=True))
    op.add_column('equipment', sa.Column('replacement_cost', sa.Float(), nullable=True))
    op.add_column('equipment', sa.Column('calibration_schedule_days', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('last_calibration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'last_calibration_date')
    op.drop_column('equipment', 'calibration_schedule_days')
    op.drop_column('equipment', 'replacement_cost')
    op.drop_column('equipment', 'expected_lifetime_years')
    op.drop_column('equipment', 'warranty_expiry')
    op.drop_column('equipment', 'purchase_date')
    # ### end Alembic commands ###
